server: 
  port: 8080
  address: localhost
  log_level: info
  workers: 2
  reload: True


sqlite:
  uri: ""
  user: ""
  pass: ""
  autocommit: false
  autoflush: false
postgres:
  uri: ""
  user: ""
  pass: ""
mysql:
  uri: ""
  user: ""
  pass: ""
