FROM python:3.13-alpine3.21 as base

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

FROM python:3.13-alpine3.21

COPY --from=base /usr/local/lib/python3.13/site-packages/ /usr/local/lib/python3.13/site-packages/

ENV PYTHONDONTWRITEBYTECODE=1

# Expose the port
EXPOSE 8080

# Default command (can be overridden in docker-compose)
ENTRYPOINT ["python3","/app/main.py"]