FROM    python:3.13.1-alpine3.21 as builder
COPY    requirements.txt .
RUN     pip install --no-cache-dir -r requirements.txt

FROM    python:3.13.1-alpine3.21
COPY    --from=builder /usr/local/lib/python3.21/site-packages /usr/local/lib/python3.21/site-packages
COPY    . /app
WORKDIR /app
CMD     ["python", "app.py"]