server: 
  host: "0.0.0.0"
  port: 8080
  address: localhost
  log_level: info
  workers: 2
  reload: True

sqlite:
  uri: "sqlite:///./backend/portfolio.db"
  autocommit: false
  autoflush: false
postgres:
  uri: "postgresql+asyncpg://portfolio:portfolio@postgres:5432/portfolio"
mysql:
  uri: ""
